#!/usr/bin/env bash
TEST_DIR=$(dirname "$0")

while sleep 1; do
  {
    find $TEST_DIR/../lib -name "*.exs";
    find $TEST_DIR/../lib -name "*.ex";
    find $TEST_DIR -name "*.exs";
    find $TEST_DIR -name "*.ex";
  } | entr -cdr $TEST_DIR/run
done
