#!/bin/bash
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
pushd $DIR/.. > /dev/null

MIX_ENV=test

ELIXIR_IS_1_3=$(elixir -v | grep 1.3)

if [ -n "$ELIXIR_IS_1_3" ]; then
  mix coveralls.travis
fi

popd > /dev/null
