#!/bin/bash
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
pushd $DIR/.. > /dev/null

MIX_ENV=test

ELIXIR_IS_1_8=$(elixir -v | grep 1.8)

if [ -n "$ELIXIR_IS_1_8" ]; then
  mix coveralls.travis
fi

popd > /dev/null
